version: '2'
services:
  extservice:
    image: nginx:latest
    hostname: owncloud.example.org
    entrypoint:
      - entrypoint.sh
      - arg1
      - arg2
    ports:
      - "9000"
    env_file:
      - ./service.env
    environment:
      - MYVAR1=val1Ext
      - MYVAR2=val2Ext
      - MYVAR3=val3Ext
    volumes:
      - "./conf.cf:/etc/target.cf"
      - "datavol:/data"
  extselfbuilt:
    build: .
volumes:
  datavol:
    external: true
