version: '2'
services:
  baseservice:
    image: alpine:latest
    hostname: service.example.org
    entrypoint:
      - entrypoint.sh
      - arg1
      - arg2
    ports:
      - "9000"
    env_file:
      - ./base.env
    environment:
      - MYBASEVAR=baseval
    volumes:
      - "./conf.cf:/etc/target.cf"
      - "datavol:/data"
  baseselfbuilt:
    build: ../docker-build
volumes:
  datavol:
    external: true
